# -*- coding: utf-8 -*-
"""Day1 capstone_exercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F03z2OpYu8cnVZzBwCrXToT96FdrMUm3

# 🏆 Capstone Exercise — Data Analysis Visual Story
**Day 1 | Session 4 | 60 minutes**

---

## Your mission
Produce a **self-contained, narrative-driven Jupyter Notebook** that takes a reader from raw data to a clear, evidence-backed conclusion using **NumPy**, **Pandas**, and at least **4 original visualisations**.

Think of it like a data journalist writing a short article — the notebook *is* the article.

---

## Choose your dataset
Pick **one** dataset below. All load with a single line of code.

| Option | Dataset | Built-in loader | Suggested question |
|---|---|---|---|
| 🌍 A | Global surface temperatures | `sns.load_dataset('geyser')` / URL below | Has global warming accelerated post-2000? |
| 🎬 B | MovieLens ratings | `sns.load_dataset('taxis')` / URL below | Which genres dominate, and has that changed? |
| 🏏 C | IPL cricket seasons | URL below | Which teams and batters are most consistent? |

```python
# Option A — Global temperature anomalies (NASA GISS)
url_A = 'https://data.giss.nasa.gov/gistemp/tabledata_v4/GLB.Ts+dSST.csv'
df = pd.read_csv(url_A, skiprows=1, na_values='***')

# Option B — Seaborn built-in movies
df = sns.load_dataset('taxis')   # if available; otherwise instructor provides CSV

# Option C — seaborn surface temperatures
df = sns.load_dataset('geyser')
```

---

## Required notebook structure

Your notebook **must** contain these 6 sections in order. Each section title is a Markdown heading.

### Section 1 — Load & Inspect (5 min)
### Section 2 — Clean & Prepare (10 min)
### Section 3 — Explore with Statistics (10 min)
### Section 4 — Visualise (20 min) ← core of the exercise
### Section 5 — Key Insights (10 min)
### Section 6 — Narrative Conclusion (5 min)

Detailed requirements for each section are in the template cells below.

---

## Grading rubric (30 points total)

| Section | Criteria | Points |
|---|---|---|
| Load & Inspect | Dataset loaded, shape printed, at least 3 inspection methods used | 3 |
| Clean & Prepare | Missing values handled with justification, at least 1 new feature engineered | 4 |
| Statistics | NumPy used for at least 2 calculations, groupby aggregation present | 4 |
| Visualise | 4 distinct chart types, all charts titled + labelled, at least 1 annotation | 10 |
| Key Insights | 3 numbered insights, each tied to a specific chart or statistic | 6 |
| Narrative | Coherent 1-paragraph conclusion written in plain English | 3 |

**Bonus (up to 3 extra points):** multi-panel dashboard, custom colour palette, interactive Plotly chart, or a fifth insight backed by a statistical test.

---
"""



# Commented out IPython magic to ensure Python compatibility.
# Setup — run this cell first
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline
plt.rcParams['figure.dpi'] = 110
sns.set_theme(style='whitegrid')

print('Libraries loaded ✅')

cust_pal = ['#F57C00', '#FFA000', '#FF9C4', '#FFE082', '#FFCA28']

"""---
## Section 1 — Load & Inspect

**Requirements:**
- Load your chosen dataset
- Print its shape
- Use at least 3 of: `.head()`, `.tail()`, `.info()`, `.describe()`, `.dtypes`, `.value_counts()` on a relevant column
- Write a 2-sentence Markdown cell describing what the dataset contains
"""

# Load your dataset here
# df = ...
df_og = sns.load_dataset('taxis')
df = df_og.copy()
# 1. Print shape
print('Shape: ', df.shape)
# 2. Show first rows
print('1st 5 rows:')
print(df.head(5))
# 3. Structural info
print('Info:')
print(df.info)
# 4. Numeric summary
print(df.describe())

print('Unique payment method: ', df['payment'].unique())
print('Unique taxi color: ', df['color'].unique())
print('Unique pickup borough: ', df['pickup_borough'].unique())
print('Unique dropoff borough: ', df['dropoff_borough'].unique())

"""*This dataset consists of the following columns: 'pickup', 'dropoff', (datetime) 'passengers' (int) <- these columns note the pickup and dropoff times alongside the number of passengers for each trip 'distance', 'fare', 'tip', 'tolls', 'total' (float), <- these note the distance and financial components of each trip, 'color', 'payment', 'pickup_zone', 'dropoff_zone', 'pickup_borough', 'dropoff_borough' (string) <- these track the colour, payment method, pick-up and drop locations for each trip. The dataset consists of cab-hailing data for 6433 trips over a period of 1 month (28th Feb to 31st March, 2019).*

---
## Section 2 — Clean & Prepare

**Requirements:**
- Identify and handle missing values — document the strategy you chose and **why**
- Drop any irrelevant columns with justification
- Engineer at least 1 new feature (e.g. decade from year, rating bucket from score, win percentage from wins/games)
- Print the shape before and after cleaning
"""

print('Shape before cleaning:', df.shape)

# Step 1 — Inspect missing values
print("Missing Data: ")
missing = df.isnull().sum()
missing_percent = 100 * df.isnull().sum() / len(df)
missing_df = pd.DataFrame({'missing': missing, 'missing_percent': missing_percent.round(2)}).sort_values(by='missing', ascending=False)
print(missing_df)

# Step 2 — Handle missing values (fillna / dropna)
df['dropoff_borough'] = df['dropoff_borough'].fillna(df['dropoff_borough'].mode()[0])
df['payment'] = df['payment'].fillna(df['payment'].mode()[0])
df['pickup_borough'] = df['pickup_borough'].fillna(df['pickup_borough'].mode()[0])
print('Imputation done.')

# Step 3 — Drop irrelevant columns
df.drop(columns=['pickup_zone'], inplace=True)
df.drop(columns=['dropoff_zone'], inplace=True)

# Step 4 — Engineer at least 1 new feature
df['IsLongDistance'] = np.where((df['pickup_borough'] != df['dropoff_borough']), True, False)
print(df.head())

print('Shape after cleaning:', df.shape)

"""*Missing data is all less than 50%, so we can impute them with the median value. The pickup and dropoff zones are not that important, the boroughs are enough, so those two can be dropped. Created a new feature to flag is a trip is long-distance (inter-borough) or not.*

---
## Section 3 — Explore with Statistics

**Requirements:**
- Use **NumPy** for at least 2 calculations (e.g. `np.percentile`, `np.corrcoef`, normalisation)
- Use **Pandas groupby** with at least 2 different aggregation functions
- Display a pivot table or cross-tabulation
- Print 3–5 interesting numbers as a formatted summary
"""

# NumPy calculations
print("Max distance covered: ", np.max(df['distance']))
print("75th percentile of passengers: ", np.percentile(df['passengers'], 75))
print("99th percentile of passengers: ", np.percentile(df['passengers'], 99))

# GroupBy aggregation
print("Method of payment in Borough Manhattan: ", df[df['pickup_borough']=='Manhattan'].groupby('payment').size().sort_values(ascending=False))
print("Method of payment where top was given: ", df[df['tip']>0].groupby('payment').size().sort_values(ascending=False))

# Pivot table or crosstab
pivot = pd.pivot_table(df, values='total', index='payment', columns='passengers', aggfunc='mean', fill_value=0)
print("Pivot Table: \n", pivot)

# Formatted summary (use f-strings or print statements)
print()
print(f"Average fare:\t ${df['fare'].mean():.2f}")
print(f"Average tip:\t ${df['tip'].mean():.2f}")
print(f"Most common payment type: {df['payment'].mode()[0]}")

"""---
## Section 4 — Visualise

**Requirements:**
- Create **4 visualisations using at least 3 distinct chart types**
- Every chart must have: a descriptive title, x-axis label, y-axis label
- At least 1 chart must include an **annotation** (arrow, text, or reference line)
- At least 1 chart must be a **multi-panel subplot** (`plt.subplots` with 2+ panels)
- Each chart is followed by a 1-sentence Markdown interpretation
"""

# Chart 1 — Bar plot
# Question this chart answers: Does payment amount depend on passenger count, and how do people prefer to pay?

fig, ax = plt.subplots(figsize=(8, 5))

# ... your code ...
sns.barplot(data=df, x='passengers', y='fare', estimator='mean', palette=cust_pal, hue='payment', alpha=0.5, errorbar=None)
ax.set_title('Total Fare vs Passengers')
ax.set_xlabel('Passengers')
ax.set_ylabel('Payment')
plt.tight_layout()
plt.show()

"""*There is no significant variance in the payment amount based on passenger count, but people seem to preder paying higher via credit cards, except as seen in the last bar, that for 6 passengers paeople paid more with cash, probably because they shared the payment.*"""

# Chart 2 — Histogram
# Question: How is fare distributed?

fig, ax = plt.subplots(figsize=(8, 5))

# ... your code ...
sns.histplot(data=df, x='fare', bins=30, palette=cust_pal, hue='payment', alpha=0.3)
ax.set_title('Total Fare Distribution by Payment Type')
plt.xlim(0,60)
ax.set_xlabel('Distance')
ax.set_ylabel('Tips')
plt.tight_layout()
plt.show()

"""*We note that most of the trips have a fare in the bin covering fare amount 5-10.*"""

# Chart 3 — Scatterplot with Annotation
# Question: Does total fare depend on distance?
ax = sns.scatterplot(data=df, x='distance', y='total', hue='payment', palette=cust_pal, alpha=0.2)
max_r = df.loc[df['total'].idxmax()]
plt.annotate('Max fare', xy=(max_r['distance'], max_r['total']),
             xytext=(max_r['distance']+2, max_r['total']+20),
            arrowprops=dict(facecolor='red', shrink=0.05),
             fontsize=12, color='red')
ax.set_title('Total Distance vs Total varied by Payment Type')
ax.set_xlabel('Distance')
ax.set_ylabel('Total')
plt.tight_layout()
plt.show()

"""*We can see a clear positive correlation vetween distance and tips, and we see that the max fare was paid in cash.*"""

# Chart 4 — must be a multi-panel figure (plt.subplots with 2+ panels)
# Questions across panels: ___

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle('First Dashboard', fontsize=13)

# Panel A
ax = axes[0]
# ...
sns.countplot(data=df, x='payment', palette=cust_pal, ax=ax, alpha=0.5)
ax.set_xlabel('Payment Method')
ax.set_ylabel('Number of Payments')
ax.set_title('Panel A')

# Panel B
ax = axes[1]
# ...
sns.violinplot(data=df, x='payment', y='fare', inner='quartile', palette=cust_pal, ax=ax, alpha=0.5)
ax.set_title('Panel B')
ax.set_xlabel('Passengers')
ax.set_ylabel('Total')
plt.ylim(-5,90)
plt.tight_layout()
plt.show()

"""*The first chart shows the number of payments via credit cards vs cash. The second chart shows the distribution of taxi fares for both payment types.*

---
## Section 5 — Key Insights

**Requirements:**
- State exactly **3 numbered insights**
- Each insight must reference a specific chart or statistic from your notebook
- Each insight must be a **single, specific, falsifiable claim** — not a vague observation

**Template:**
```
1. [Specific claim] — supported by [Chart X / the groupby in Section 3].
2. ...
3. ...
```

**Example (good):** "First-class passengers were 2.5× more likely to survive than third-class passengers (62% vs 24%), as shown in Chart 1."

**Example (bad):** "The data shows interesting patterns across different groups."

**Insight 1:** *Payment amount does not differ much based on passenger count, but people mostly seem to prefer paying higher bills in card - Chart 1.*

**Insight 2:** *Greater the distance, greater the tip. - Chart 3*

**Insight 3:** *Most of the payments were made via credit card - Chart 4 Graph 1*

---
## Section 6 — Narrative Conclusion

**Requirements:**
- Write **one paragraph (4–6 sentences)** in plain English
- Synthesise your 3 insights into a coherent story
- State what a decision-maker could *do* with this finding — or what question to investigate next
- No code in this cell — pure prose

*Most people taking this cab service paid through credit cards. However, for a larder number of passengers sharing a ride, they preferred sharing the payment amount. Hence, more payments, though higher in amount at this level, were made in cash. A stakeholder might be tempted to work on streamlining the credit card payment method, ensuring that that window is not disrupted as that has the chance of severely impactinh revenue. We should aslo inspect the most commont pickup and dropoff boroughs so that we may concentrate more cabs in those areas to match supply to demand.*

---
## 🌟 Bonus Challenges

If you finish early, attempt any of the following for extra credit:

1. **Dashboard panel:** Combine all 4 charts into a single `plt.subplots(2, 2)` figure saved as a PNG.
2. **Custom palette:** Define a 5-colour hex palette and apply it consistently across all charts.
3. **Interactive chart:** Recreate one chart using `plotly.express` — hover tooltips count as annotation.
4. **Statistical test:** Run a t-test or Mann-Whitney U test to confirm one of your insights (import from `scipy.stats`).
5. **Storytelling:** Add a Markdown cell *before each chart* posing the question the chart will answer — making the notebook feel like a news article.
"""

#Dshboard 1
# Chart 4 — must be a multi-panel figure (plt.subplots with 2+ panels)
# Questions across panels: ___

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Bigger Dashboard', fontsize=13)

# Panel A
ax = axes[0][0]
sns.barplot(data=df, x='passengers', y='fare', estimator='mean', palette=cust_pal, hue='payment', alpha=0.5, errorbar=None, ax=ax)
ax.set_xlabel('Passengers')
ax.set_ylabel('Payment')
ax.set_title('Panel A')

# Panel B
ax = axes[0][1]
ax.set_title('Panel B')
sns.histplot(data=df, x='fare', bins=30, palette=cust_pal, hue='payment', alpha=0.3, ax=ax)
plt.xlim(0,60)
ax.set_xlabel('Distance')
ax.set_ylabel('Tips')

ax = axes[0][2]
ax.set_title('Panel C')
sns.scatterplot(data=df, x='distance', y='total', hue='payment', palette=cust_pal, alpha=0.2, ax=ax)
max_r = df.loc[df['total'].idxmax()]
plt.annotate('Max fare', xy=(max_r['distance'], max_r['total']),
             xytext=(max_r['distance']+2, max_r['total']+20),
            arrowprops=dict(facecolor='red', shrink=0.05),
             fontsize=12, color='red')
ax.set_title('Total Distance vs Total varied by Payment Type')
ax.set_xlabel('Distance')
ax.set_ylabel('Total')

ax = axes[1][0]
sns.countplot(data=df, x='payment', palette=cust_pal, ax=ax, alpha=0.5)
ax.set_xlabel('Payment Method')
ax.set_ylabel('Number of Payments')
ax.set_title('Panel D')

ax = axes[1][1]
sns.violinplot(data=df, x='payment', y='fare', inner='quartile', palette=cust_pal, ax=ax, alpha=0.5)
ax.set_title('Panel E')
ax.set_xlabel('Passengers')
ax.set_ylabel('Total')
plt.ylim(-5,90)

plt.tight_layout()
plt.savefig('big_dashboard.png')
plt.show()

import plotly.offline as pyo
import plotly.express as py
pyo.init_notebook_mode()
fig=py.histogram(df, x='fare', nbins=30, title='Total Distance vs Tips varied by Payment Type', color_discrete_sequence=['#FFA000'], opacity=0.3)
fig.update_layout(xaxis_title='Fare Amount', yaxis_title='Frequency', template='plotly_white')
fig.show()