# -*- coding: utf-8 -*-
"""multi_agent_observability_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UcWdjMEByecfPhSfXGRh4ibPD4cWjsmC
"""

import json
import random
import time
import uuid
from datetime import datetime


def log_event(event_type, **data):
    """
    Emit structured JSON logs.
    """
    payload = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "event": event_type,
        **data
    }

    print(json.dumps(payload))


class ProgressListener:
    """
    Emits throttled progress updates (~25% intervals).
    Also tracks the latest step reached for failure reporting.
    """

    def __init__(self, trace_id, span_id):
        self.trace_id = trace_id
        self.span_id = span_id
        self.last_bucket = 0
        self.last_step = 0

    def __call__(self, agent_name, step, total_steps):
        self.last_step = step

        percent_complete = (step / total_steps) * 100

        bucket = int(percent_complete // 25)

        if bucket > self.last_bucket:
            self.last_bucket = bucket

            log_event(
                "agent_progress",
                trace_id=self.trace_id,
                span_id=self.span_id,
                agent=agent_name,
                step=step,
                total_steps=total_steps,
                percent_complete=round(percent_complete, 2)
            )


class Agent:
    """
    Simulated agent performing N steps.
    """

    def __init__(self, name, steps, fail_at_step=None):
        self.name = name
        self.steps = steps
        self.fail_at_step = fail_at_step

    def run(self, listener):
        for step in range(1, self.steps + 1):

            time.sleep(random.uniform(0.05, 0.20))

            if self.fail_at_step and step == self.fail_at_step:
                raise RuntimeError(
                    f"{self.name} failed at step {step}"
                )

            listener(
                self.name,
                step,
                self.steps
            )


class Orchestrator:
    """
    Runs agents sequentially while emitting observability events.
    """

    def __init__(self, agents):
        self.agents = agents

    def run(self):

        trace_id = str(uuid.uuid4())

        total_pipeline_steps = sum(
            agent.steps for agent in self.agents
        )

        completed_pipeline_steps = 0

        run_start = time.time()

        try:

            for agent in self.agents:

                span_id = str(uuid.uuid4())

                listener = ProgressListener(
                    trace_id,
                    span_id
                )

                agent_start = time.time()

                log_event(
                    "agent_started",
                    trace_id=trace_id,
                    span_id=span_id,
                    agent=agent.name
                )

                try:

                    agent.run(listener)

                    agent_duration = (
                        time.time() - agent_start
                    )

                    agent_throughput = (
                        agent.steps / agent_duration
                    )

                    completed_pipeline_steps += agent.steps

                    pipeline_percent = (
                        completed_pipeline_steps
                        / total_pipeline_steps
                    ) * 100

                    log_event(
                        "agent_completed",
                        trace_id=trace_id,
                        span_id=span_id,
                        agent=agent.name,
                        duration_seconds=round(
                            agent_duration,
                            3
                        ),
                        throughput_steps_per_sec=round(
                            agent_throughput,
                            2
                        ),
                        pipeline_percent_complete=round(
                            pipeline_percent,
                            2
                        )
                    )

                except Exception as e:

                    pipeline_steps_at_failure = (
                        completed_pipeline_steps
                        + listener.last_step
                    )

                    pipeline_percent = (
                        pipeline_steps_at_failure
                        / total_pipeline_steps
                    ) * 100

                    log_event(
                        "agent_failed",
                        trace_id=trace_id,
                        span_id=span_id,
                        agent=agent.name,
                        failed_step=listener.last_step,
                        pipeline_percent_complete=round(
                            pipeline_percent,
                            2
                        ),
                        error=str(e)
                    )

                    raise

            run_duration = time.time() - run_start

            pipeline_throughput = (
                total_pipeline_steps / run_duration
            )

            log_event(
                "run_summary",
                trace_id=trace_id,
                status="success",
                total_agents=len(self.agents),
                total_steps=total_pipeline_steps,
                total_duration_seconds=round(
                    run_duration,
                    3
                ),
                pipeline_throughput_steps_per_sec=round(
                    pipeline_throughput,
                    2
                ),
                pipeline_percent_complete=100.0
            )

        except Exception:

            run_duration = time.time() - run_start

            pipeline_throughput = (
                completed_pipeline_steps
                / run_duration
                if run_duration > 0
                else 0
            )

            log_event(
                "run_summary",
                trace_id=trace_id,
                status="failed",
                total_agents=len(self.agents),
                total_steps=total_pipeline_steps,
                completed_steps=completed_pipeline_steps,
                total_duration_seconds=round(
                    run_duration,
                    3
                ),
                pipeline_throughput_steps_per_sec=round(
                    pipeline_throughput,
                    2
                )
            )

            print("\nPipeline terminated due to failure.\n")


def main():

    # SUCCESS SCENARIO
    agents = [
        Agent("Planner", 3),
        Agent("Researcher", 6),
        Agent("Writer", 4),
        Agent("Reviewer", 2)
    ]

    # FAILURE SCENARIO
    # agents = [
    #     Agent("Planner", 3),
    #     Agent("Researcher", 6),
    #     Agent("Writer", 4, fail_at_step=3),
    #     Agent("Reviewer", 2)
    # ]

    orchestrator = Orchestrator(agents)
    orchestrator.run()


if __name__ == "__main__":
    main()

