# -*- coding: utf-8 -*-
"""Colab2_Orchestration_Patterns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Klw9gki7EVAoKX1jjHl1aJPEtbkQjKVm

# Colab 2 · Orchestration Patterns in Depth
### Day 19 — Agent Orchestration with AutoGen Studio & Semantic Kernel

Colab 1 used the simplest pattern (RoundRobin). Now you'll wire the **same research team four different ways** and watch how the *control flow* changes — then peek at the **same idea in Semantic Kernel**.

**You will build:**
1. **SelectorGroupChat** — an LLM decides who speaks next.
2. **Swarm** — agents hand off to each other directly.
3. **GraphFlow** — a deterministic researcher → writer → reviewer graph.
4. A **function tool** the researcher calls to delegate real work.
5. A **Semantic Kernel** sequential-orchestration mini-example.

⏱️ ~60 min including the extension tasks at the end.

> The patterns are the lesson. AutoGen, Semantic Kernel and the Microsoft Agent Framework all expose this same family — RoundRobin/Sequential, Selector/GroupChat, Swarm/Handoff, Graph, Magentic.

## 0 · Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U "autogen-agentchat" "autogen-ext[openai]"
print("AutoGen installed.")

import os
from getpass import getpass
from google.colab import userdata

if not os.environ.get("OPENAI_API_KEY"):
    os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

from autogen_ext.models.openai import OpenAIChatCompletionClient
from autogen_agentchat.agents import AssistantAgent
from autogen_agentchat.conditions import TextMentionTermination, MaxMessageTermination
from autogen_agentchat.ui import Console

model_client = OpenAIChatCompletionClient(model="gpt-4o-mini")
print("Ready.")

"""### Three specialists we'll reuse

Notice the **descriptions** — Selector and Swarm route work based on them, so they have to be specific and non-overlapping.
"""

def make_specialists():
    planner = AssistantAgent(
        name="planner",
        model_client=model_client,
        description="Breaks a topic into 2-3 concrete sub-questions to research.",
        system_message="You plan research. Given a topic, list 2-3 specific sub-questions. Keep it short.",
    )
    researcher = AssistantAgent(
        name="researcher",
        model_client=model_client,
        description="Answers factual sub-questions with concise bullet points.",
        system_message="You answer the planner's sub-questions with short factual bullets.",
    )
    writer = AssistantAgent(
        name="writer",
        model_client=model_client,
        description="Turns research bullets into a tight 4-sentence summary, ending with APPROVE.",
        system_message="Write a tight 4-sentence summary from the research. End your message with APPROVE.",
    )
    return planner, researcher, writer

print("Specialist factory ready.")

"""## 1 · SelectorGroupChat — let an LLM route

Instead of a fixed order, a **SelectorGroupChat** uses a model to pick *who should act next* based on the conversation and each agent's `description`. Good when the next best speaker depends on what just happened.

Key knobs: it needs its own `model_client` to do the routing, and `allow_repeated_speaker=False` stops one agent from monopolising the floor.
"""

from autogen_agentchat.teams import SelectorGroupChat

planner, researcher, writer = make_specialists()
termination = TextMentionTermination("APPROVE") | MaxMessageTermination(8)

selector_team = SelectorGroupChat(
    participants=[planner, researcher, writer],
    model_client=model_client,        # the "router" brain
    termination_condition=termination,
    allow_repeated_speaker=False,
)

await Console(selector_team.run_stream(
    task="Topic: why are reusable cups better than disposable ones?"
))

"""Look at the speaker order in the transcript — it was **chosen at runtime**, not fixed. That's the difference from RoundRobin.

## 2 · Swarm — agents hand off to each other

In a **Swarm**, control is decentralised: each agent declares who it can **hand off** to via `handoffs=[...]`, and passes control with a handoff message. There's no central router — the agents themselves decide.

We'll build a tiny triage flow: a `triage` agent routes to either `billing` or `tech`, and those can hand back to the user when done.
"""

from autogen_agentchat.teams import Swarm
from autogen_agentchat.conditions import HandoffTermination

triage = AssistantAgent(
    name="triage",
    model_client=model_client,
    handoffs=["billing", "tech"],
    description="Front desk: routes the user to the right specialist.",
    system_message="Decide if the request is about billing or tech, then hand off to that agent.",
)
billing = AssistantAgent(
    name="billing",
    model_client=model_client,
    handoffs=["triage"],
    description="Handles billing and refund questions.",
    system_message="Answer the billing question. If it's not billing, hand back to triage.",
)
tech = AssistantAgent(
    name="tech",
    model_client=model_client,
    handoffs=["triage"],
    description="Handles technical troubleshooting.",
    system_message="Answer the tech question concisely, then say DONE.",
)

swarm = Swarm(
    participants=[triage, billing, tech],          # Swarm starts with the first agent
    termination_condition=TextMentionTermination("DONE") | MaxMessageTermination(8),
)

await Console(swarm.run_stream(task="My app keeps crashing when I open the camera."))

"""Watch for the **HandoffMessage** in the transcript — that's one agent explicitly delegating to another. `HandoffTermination(target="user")` is another common stop condition when an agent hands control back to a human.

## 3 · GraphFlow — a deterministic workflow

When you need the **same path every time** (auditable, reproducible), use **GraphFlow**. You declare nodes and directed edges with `DiGraphBuilder`; execution follows the graph exactly.

Here: `planner → researcher → writer`, a fixed pipeline with no LLM routing brain.
"""

from autogen_agentchat.teams import DiGraphBuilder, GraphFlow

planner, researcher, writer = make_specialists()

builder = DiGraphBuilder()
builder.add_node(planner).add_node(researcher).add_node(writer)
builder.add_edge(planner, researcher).add_edge(researcher, writer)
graph = builder.build()

flow = GraphFlow(
    participants=builder.get_participants(),
    graph=graph,
)

await Console(flow.run_stream(task="Topic: the benefits of cycling to work."))

"""GraphFlow gives you **determinism**: the order is guaranteed by the graph, not decided by a model. That's exactly what you want for a compliance-sensitive or repeatable pipeline.

## 4 · A function tool the researcher can call

Delegation isn't only agent-to-agent — an agent can delegate to **code** via a tool. Define a plain Python function, pass it in `tools=[...]`, and the agent will call it when useful. (Here it's a stub; swap in a real search API at home.)
"""

def web_search(query: str) -> str:
    """Look up a query and return a short text snippet. (Stub for the workshop.)"""
    canned = {
        "reusable cup co2": "A reusable cup typically breaks even vs. disposables after ~20-100 uses.",
        "default": "No exact match; returning a generic note that reusable goods amortise their footprint with use.",
    }
    return canned.get(query.lower().strip(), canned["default"])

researcher_with_tool = AssistantAgent(
    name="researcher",
    model_client=model_client,
    tools=[web_search],
    description="Researches facts, calling web_search when it needs evidence.",
    system_message="Use the web_search tool to find a figure, then report it in one bullet. End with APPROVE.",
)

from autogen_agentchat.teams import RoundRobinGroupChat
tool_team = RoundRobinGroupChat(
    [researcher_with_tool],
    termination_condition=TextMentionTermination("APPROVE") | MaxMessageTermination(4),
)
await Console(tool_team.run_stream(task="Find a figure on reusable cup CO2 break-even and report it."))

"""The transcript shows a **ToolCall** and its result — the agent delegated part of its job to your function. In production you'd scope tools to least privilege and validate their arguments.

## 5 · The same idea in Semantic Kernel

Semantic Kernel expresses these patterns too — its **Sequential** orchestration is the SK analogue of RoundRobin/GraphFlow-in-a-line. The code below shows the *shape* of SK agent orchestration.

> ⚠️ SK's agent-orchestration API is newer and evolving (and SK is in maintenance mode heading into the Microsoft Agent Framework). If an import path has moved, check the official Semantic Kernel docs — the **concept** is what transfers, not the exact symbol names.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q -U semantic-kernel
print("Semantic Kernel installed.")

# The shape of an SK sequential orchestration: two agents, output of one feeds the next.
# Wrapped in try/except because SK's orchestration symbols move between versions.
import asyncio

try:
    from semantic_kernel.agents import ChatCompletionAgent
    from semantic_kernel.agents.orchestration.sequential import SequentialOrchestration
    from semantic_kernel.agents.runtime import InProcessRuntime
    from semantic_kernel.connectors.ai.open_ai import OpenAIChatCompletion

    service = OpenAIChatCompletion(ai_model_id="gpt-4o-mini")

    sk_writer = ChatCompletionAgent(
        name="writer", service=service,
        instructions="Write one short paragraph on the given topic.",
    )
    sk_editor = ChatCompletionAgent(
        name="editor", service=service,
        instructions="Tighten the paragraph you receive into two crisp sentences.",
    )

    orchestration = SequentialOrchestration(members=[sk_writer, sk_editor])
    runtime = InProcessRuntime()
    runtime.start()

    result = await orchestration.invoke(
        task="The benefits of walking meetings.", runtime=runtime
    )
    print(await result.get())
    await runtime.stop_when_idle()

except Exception as e:
    print("SK orchestration symbols may have moved in your installed version.")
    print("Concept: members=[writer, editor] run in sequence, output -> input.")
    print("Check https://learn.microsoft.com/semantic-kernel for the current API.")
    print("Error was:", type(e).__name__, e)

"""Notice the **identical mental model**: a list of agents, run in order, each one's output feeding the next. RoundRobin (AutoGen) ≈ Sequential (SK) ≈ a linear GraphFlow. Learn it once.

---
## 🚀 Extension tasks

### Extension 1 — Write a custom selector function
`SelectorGroupChat` accepts a `selector_func` that overrides the LLM router with your own logic. Write a function that **forces** `planner` to go first, then lets the model choose. (Signature: it receives the message history and returns the next speaker's name, or `None` to defer to the model.)

### Extension 2 — Add a conditional GraphFlow edge
Extend the graph from §3 with a **reviewer** node and a **conditional edge**: if the writer's output contains the word `REVISE`, loop back to the writer; otherwise finish. Use `DiGraphBuilder`'s conditional-edge support and a stop condition so it can't loop forever.

### Extension 3 — Nest a team inside a graph node
A node in a GraphFlow can itself be a **team**. Replace the single `researcher` node with a 2-agent `RoundRobinGroupChat` (researcher + fact-checker) and wire that team in as one node. This is *composition*: patterns nest inside patterns.

Scaffolds below.
"""

#Extension 1
def force_planner_first(messages):
    # Return an agent name (str) to force a speaker, or None to let the model decide.
    if len(messages) <= 1:
        return "planner"
    return None

planner, researcher, writer = make_specialists()
team = SelectorGroupChat(
    participants=[planner, researcher, writer],
    model_client=model_client,
    selector_func=force_planner_first,
    termination_condition=TextMentionTermination("APPROVE") | MaxMessageTermination(8),
)
await Console(team.run_stream(task="Topic: benefits of a standing desk."))

#Extension 3
fact_checker = AssistantAgent(
    name="fact_checker",
    model_client=model_client,
    description="Verifies factual claims in research output.",
    system_message="You are a diligent fact-checker. Review the provided research output for accuracy and consistency. If correct, say 'FACTS CHECKED.' If incorrect, highlight the inaccuracy and say 'NEEDS REVISION.'",
)

from autogen_agentchat.messages import TextMessage
from typing import Any

class TeamChatAgent(AssistantAgent):
    """A wrapper to allow a GroupChat (like RoundRobinGroupChat) to act as a single ChatAgent node."""
    def __init__(self, name: str, team: Any, model_client: Any, **kwargs):
        super().__init__(
            name=name,
            model_client=model_client,  # Use the provided model_client directly
            description=kwargs.pop("description", f"A team agent that orchestrates {team.name}."),
            system_message=kwargs.pop("system_message", "You are an orchestrator for a sub-team."),
            **kwargs
        )
        self.team = team

    async def send(self, message: Any, recipient: Any) -> None:
        # GroupChat's run_stream expects the initiating message from 'user' or similar.
        # We need to extract the content and potentially set it as the task.
        task_content = message.to_text()

        # Run the internal team with the message content as the task
        print(f"\n>>> TeamChatAgent '{self.name}' running internal team '{self.team.name}' with task: {task_content}\n")
        result = await self.team.run_stream(task=task_content)

        # Get the last message from the internal team's execution
        if result.messages:
            last_team_message = result.messages[-1]
            response_content = last_team_message.to_text()
            # Send the internal team's final response back to the recipient
            await recipient.receive(TextMessage(content=response_content, sender=self))
        else:
            print(f"Warning: Internal team '{self.team.name}' produced no messages.")
            await recipient.receive(TextMessage(content="Internal team finished without a clear response.", sender=self))

    # The receive method should be defined to complete the ChatAgent interface.
    # For simplicity, we can just print received messages or log them.
    # In a more complex scenario, this might trigger internal team actions.
    async def receive(self, message: Any, sender: Any) -> None:
        # For simplicity, we can just print received messages or log them.
        # In a more complex scenario, this might trigger internal team actions.
        print(f"TeamChatAgent '{self.name}' received message from {sender.name}: {message.to_text()})")

"""Now, with the `TeamChatAgent` wrapper, I will modify the `research_team` definition to use this new agent and integrate it into the `GraphFlow`."""

research_inner_team = RoundRobinGroupChat(
    [researcher, fact_checker],
    termination_condition=MaxMessageTermination(4),
)

research_team_node = TeamChatAgent(
    name="research_orchestrator",
    team=research_inner_team,
    description="Orchestrates a research sub-team to gather and fact-check information.",
    system_message="You lead a research and fact-checking sub-team. Your role is to get verified information."
)

builder = DiGraphBuilder()
builder.add_node(planner).add_node(research_team_node).add_node(writer)
builder.add_edge(planner, research_team_node).add_edge(research_team_node, writer)
graph = builder.build()
flow = GraphFlow(
    participants=builder.get_participants(),
    graph=graph,
    termination_condition=TextMentionTermination("APPROVE") | MaxMessageTermination(8)
)

await Console(flow.run_stream(task="Topic: the environmental impact of fast fashion."))

research_inner_team = RoundRobinGroupChat(
    [researcher, fact_checker],
    termination_condition=MaxMessageTermination(4),
)

research_team_node = TeamChatAgent(
    name="research_orchestrator",
    team=research_inner_team,
    model_client=model_client, # Added model_client to TeamChatAgent instantiation
    description="Orchestrates a research sub-team to gather and fact-check information.",
    system_message="You lead a research and fact-checking sub-team. Your role is to get verified information."
)

builder = DiGraphBuilder()
builder.add_node(planner).add_node(research_team_node).add_node(writer)
builder.add_edge(planner, research_team_node).add_edge(research_team_node, writer)
graph = builder.build()
flow = GraphFlow(
    participants=builder.get_participants(),
    graph=graph,
    termination_condition=TextMentionTermination("APPROVE") | MaxMessageTermination(8)
)

await Console(flow.run_stream(task="Topic: the environmental impact of fast fashion."))

await model_client.close()
print("Client closed. On to the capstone!")

