# -*- coding: utf-8 -*-
"""ext2_human_in_loop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FyNL8iRhQFeIof8u5qNYdp9UCjwXnXe9
"""

!pip install -q langgraph langchain-core

from typing import TypedDict, Optional

from langgraph.graph import StateGraph, END
from langgraph.types import interrupt, Command
from langgraph.checkpoint.memory import InMemorySaver


# =====================================================
# STATE
# =====================================================

class LoanState(TypedDict):
    application_id: str
    loan_amount: float
    applicant_summary: str
    risk_score: float

    review_required: bool
    decision: Optional[str]
    reviewer_id: Optional[str]
    review_notes: Optional[str]


# =====================================================
# CONFIG
# =====================================================

HIGH_VALUE_THRESHOLD = 1_000_000   # ₹10 Lakhs
HIGH_RISK_THRESHOLD = 0.70


# =====================================================
# NODES
# =====================================================

def route_loan(state: LoanState):
    """
    Decide whether human review is required.
    """

    review_required = (
        state["loan_amount"] >= HIGH_VALUE_THRESHOLD
        or state["risk_score"] >= HIGH_RISK_THRESHOLD
    )

    print(
        f"\nRouting Loan [{state['application_id']}]\n"
        f"Amount: ₹{state['loan_amount']:,.0f}\n"
        f"Risk Score: {state['risk_score']:.2f}"
    )

    if review_required:
        print("→ Requires HUMAN REVIEW")
    else:
        print("→ Eligible for AUTO PROCESSING")

    return {
        **state,
        "review_required": review_required
    }


def auto_process(state: LoanState):
    """
    Auto-approve low-risk loans.
    """

    print("\n⚡ Auto-processing loan")

    return {
        **state,
        "decision": "approved_auto",
        "reviewer_id": "SYSTEM",
        "review_notes": "Automatically approved"
    }


def human_review(state: LoanState):
    """
    Pause graph and wait for human decision.
    """

    print("\n⏸ Waiting for human review...")

    review_data = interrupt(
        {
            "application_id": state["application_id"],
            "loan_amount": state["loan_amount"],
            "risk_score": state["risk_score"],
            "summary": state["applicant_summary"]
        }
    )

    print(
        f"\n👤 Human Decision Received: "
        f"{review_data['decision'].upper()}"
    )

    return {
        **state,
        "decision": review_data["decision"],
        "reviewer_id": review_data["reviewer_id"],
        "review_notes": review_data.get("notes", "")
    }


# =====================================================
# ROUTER
# =====================================================

def review_router(state: LoanState):

    if state["review_required"]:
        return "human_review"

    return "auto_process"


# =====================================================
# BUILD GRAPH
# =====================================================

builder = StateGraph(LoanState)

builder.add_node("route", route_loan)
builder.add_node("auto_process", auto_process)
builder.add_node("human_review", human_review)

builder.set_entry_point("route")

builder.add_conditional_edges(
    "route",
    review_router,
    {
        "auto_process": "auto_process",
        "human_review": "human_review"
    }
)

builder.add_edge("auto_process", END)
builder.add_edge("human_review", END)

memory = InMemorySaver()

graph = builder.compile(
    checkpointer=memory
)

print("✅ Graph compiled successfully")


# =====================================================
# TEST DATA
# =====================================================

test_loans = [
    {
        "application_id": "APP100301",
        "loan_amount": 500_000,
        "applicant_summary": "Salaried, credit score 720",
        "risk_score": 0.25,
        "review_required": False,
        "decision": None,
        "reviewer_id": None,
        "review_notes": None,
    },

    {
        "application_id": "APP100302",
        "loan_amount": 1_500_000,
        "applicant_summary": "Self-employed, credit score 660",
        "risk_score": 0.62,
        "review_required": False,
        "decision": None,
        "reviewer_id": None,
        "review_notes": None,
    },

    {
        "application_id": "APP100303",
        "loan_amount": 200_000,
        "applicant_summary": "Credit score 580",
        "risk_score": 0.82,
        "review_required": False,
        "decision": None,
        "reviewer_id": None,
        "review_notes": None,
    }
]


# =====================================================
# PROCESS LOANS
# =====================================================

for idx, loan in enumerate(test_loans, start=1):

    print("\n" + "=" * 60)

    thread_id = f"loan-{idx}"

    config = {
        "configurable": {
            "thread_id": thread_id
        }
    }

    result = graph.invoke(
        loan,
        config=config
    )

    # -------------------------------------------------
    # AUTO PATH
    # -------------------------------------------------

    if "__interrupt__" not in result:

        print("\n✅ FINAL RESULT")
        print(result)
        continue

    # -------------------------------------------------
    # HUMAN REVIEW PATH
    # -------------------------------------------------

    interrupt_data = result["__interrupt__"][0].value

    print("\n📋 Review Package")
    print(interrupt_data)

    # Simulated human reviewer
    if interrupt_data["risk_score"] < 0.70:
        review = {
            "decision": "approve",
            "reviewer_id": "UNDERWRITER_001",
            "notes": "Income verified"
        }
    else:
        review = {
            "decision": "reject",
            "reviewer_id": "UNDERWRITER_002",
            "notes": "Risk exceeds policy threshold"
        }

    print("\n👤 Simulated Reviewer Decision")
    print(review)

    final_result = graph.invoke(
        Command(resume=review),
        config=config
    )

    print("\n✅ FINAL RESULT")
    print(final_result)


# =====================================================
# OPTIONAL GRAPH VISUALIZATION
# =====================================================

try:
    from IPython.display import Image, display

    display(
        Image(
            graph.get_graph().draw_mermaid_png()
        )
    )

except Exception:
    pass

